### ISSUE TITLE
TouchWrap plugin can corrupt user's projects

### ISSUE THREAD

**Issue by AshleyScirra** [rexrainbow/C3Plugins#1]
A user reported to us a corrupt C3 project, and it turns out it's something to do with the fact they use the TouchWrap plugin. It was failing to open because somehow there was a string value for one of the check properties (which ought to be a boolean) and was causing a type check to fail during loading.

The user was in a bit of a panic and we ended up supporting them and recovering their project for them. This is why we don't like copy-pasting official addons and modifying them; the compatibility problems are usually worse than any benefit of the addon.

I'm not sure how this happened but you might want to make use of LoadC2Property to ensure C2 properties are imported as expected in to C3.

**Comment by rexrainbow** [comment]
I convert the comb property (No|Yes) to comb property before, but I found
that kind of property is nice to be check box, thus I change comb property
to be checkbox.
It worked fine if starting c2 project or starting a new c3 project, but it
might have error when that c2 project has been opened in c3.

A possible way is change comb property back for these case. Or add some
wrap action for some kind of properties. For example, check box <--> comb
box.

BTW, font property is not the same in c2 and c3.

2018-01-26 19:23 GMT+08:00 Ashley (Scirra) <notifications@github.com>:

**Comment by rexrainbow** [comment]
Moreover it is not the problem of forking problem as I said before, do
noting is worse.
Tell me if you though that kind of plugin makers is not welcome. Then I
will stop making any new plugin. It is fine.

2018-01-26 22:16 GMT+08:00 Pin-Hua Tien <binhua.tein@gmail.com>:

**Comment by AshleyScirra** [comment]
I only want plugin developers to stop forking the official addons. This has been my advice for over 5 years: https://www.scirra.com/forum/please-do-not-adjust-official-plugins-or-behaviors_t71650
