### ISSUE TITLE
rex_text_typing_and_rex_timeline - please switch these two plugins with c2runtime to c3runtime

### ISSUE THREAD

**Issue by Roguelike2018** [rexrainbow/C3Plugins#2]
[rex_text_typing_and_rex_timeline.zip](https://github.com/rexrainbow/C3Plugins/files/2842198/rex_text_typing_and_rex_timeline.zip)

**Comment by rexrainbow** [comment]
No support now, sorry.

**Comment by Roguelike2018** [comment]
> No support now, sorry.

and when you can rewrite it in c3runtime

**Comment by rexrainbow** [comment]
I had left scirra communit 1 year, and I won't go back.

**Comment by Roguelike2018** [comment]
> I had left scirra communit 1 year, and I won't go back.

sadly

what should I do then?
